---
title: "senomiR_aging_tissues"
output: html_document
date: "2023-07-01"
---
```{r}
library(venn)
library(tidygraph)
library(VennDiagram)
library(UpSetR)
library(stringr)
library(ggplot2)
library(gridExtra)
library(ComplexHeatmap)
#load microRNA DE data CELL

miRNA_CELL_ASC <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_miRNA_ASC.txt", header = TRUE, sep = "\t", dec = ".")
miRNA_CELL_HDF <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_miRNA_HDF.txt", header = TRUE, sep = "\t", dec = ".")
miRNA_CELL_HDMVEC <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_miRNA_HDMVEC.txt", header = TRUE, sep = "\t", dec = ".")
miRNA_CELL_HUVEC <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_miRNA_HUVEC.txt", header = TRUE, sep = "\t", dec = ".")
miRNA_CELL_RPTEC <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_miRNA_RPTEC.txt", header = TRUE, sep = "\t", dec = ".")

miRNA_CELL_ASC$miRNA <- as.factor(miRNA_CELL_ASC$miRNA)
miRNA_CELL_HDF$miRNA <- as.factor(miRNA_CELL_HDF$miRNA)
miRNA_CELL_HDMVEC$miRNA <- as.factor(miRNA_CELL_HDMVEC$miRNA)
miRNA_CELL_HUVEC$miRNA <- as.factor(miRNA_CELL_HUVEC$miRNA)
miRNA_CELL_RPTEC$miRNA <- as.factor(miRNA_CELL_RPTEC$miRNA)

#load gene expression DE data
gene_ASC <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_gene_ASC.txt", header = TRUE, sep = "\t", dec = ",")
gene_HDF <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_gene_HDF.txt", header = TRUE, sep = "\t", dec = ",")
gene_HDMVEC <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_gene_HDMVEC.txt", header = TRUE, sep = "\t", dec = ",")
gene_HUVEC <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_gene_HUVEC.txt", header = TRUE, sep = "\t", dec = ",")
gene_RPTEC <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_gene_RPTEC.txt", header = TRUE, sep = "\t", dec = ",")

gene_ASC$external_gene_name <- as.factor(gene_ASC$external_gene_name)
gene_HDF$external_gene_name <- as.factor(gene_HDF$external_gene_name)
gene_HDMVEC$external_gene_name <- as.factor(gene_HDMVEC$external_gene_name)
gene_HUVEC$external_gene_name <- as.factor(gene_HUVEC$external_gene_name)
gene_RPTEC$external_gene_name <- as.factor(gene_RPTEC$external_gene_name)

gene_ASC$external_gene_name <- as.factor(gene_ASC$gene)
gene_HDF$external_gene_name <- as.factor(gene_HDF$gene)
gene_HDMVEC$external_gene_name <- as.factor(gene_HDMVEC$gene)
gene_HUVEC$external_gene_name <- as.factor(gene_HUVEC$gene)
gene_RPTEC$external_gene_name <- as.factor(gene_RPTEC$gene)

##microRNA data
#remove spike-ins
spike_ins <- c("#C", "#E", "#H", "#I", "#K", "#M", "#N", "#uniSp.2", "#uniSp.4", "#uniSp.5")
selection <- c("ASC", "HDF", "HDMVEC", "HUVEC", "RPTEC")
matrix <- c("CELL")

df_list <- list(miRNA_CELL_ASC, miRNA_CELL_HDF, miRNA_CELL_HDMVEC, miRNA_CELL_HUVEC, miRNA_CELL_RPTEC)

names(df_list) <- c("miRNA_CELL_ASC", "miRNA_CELL_HDF", "miRNA_CELL_HDMVEC", "miRNA_CELL_HUVEC", "miRNA_CELL_RPTEC")

loop.selection <- c(paste("miRNA_", as.vector(outer(matrix, selection, paste, sep="_")), sep = ""))

df_list_select <- list()
for (i in loop.selection) {
  df_list_select[[i]] <- df_list[[i]][!df_list[[i]]$miRNA %in% spike_ins,]
}

df_list_up <- list()
for (i in names(df_list_select)) {
  df_list_up[[i]] <- df_list_select[[i]][df_list_select[[i]]$FDR < 0.15 & df_list_select[[i]]$logFC > 0,]$miRNA
}

df_list_down <- list()
for (i in names(df_list_select)) {
  df_list_down[[i]] <- df_list_select[[i]][df_list_select[[i]]$FDR < 0.15 & df_list_select[[i]]$logFC < 0,]$miRNA
}

##gene data
df_list_gene <- list(gene_ASC, gene_HDF, gene_HDMVEC, gene_HUVEC, gene_RPTEC)
names(df_list_gene) <- c("gene_ASC", "gene_HDF", "gene_HDMVEC", "gene_HUVEC", "gene_RPTEC")

df_list_gene_up <- list()
for (i in names(df_list_gene)) {
  df_list_gene_up[[i]] <- df_list_gene[[i]][df_list_gene[[i]]$FDR < 0.15 & df_list_gene[[i]]$logFC > 0,]$gene
}

df_list_gene_down <- list()
for (i in names(df_list_gene)) {
  df_list_gene_down[[i]] <- df_list_gene[[i]][df_list_gene[[i]]$FDR < 0.15 & df_list_gene[[i]]$logFC < 0,]$gene
}

names(df_list_up) <- c("ASC", "HDF", "HDMVEC", "HUVEC", "RPTEC")
names(df_list_down) <- c("ASC", "HDF", "HDMVEC", "HUVEC", "RPTEC")
names(df_list_gene_up) <- c("ASC", "HDF", "HDMVEC", "HUVEC", "RPTEC")
names(df_list_gene_down) <- c("ASC", "HDF", "HDMVEC", "HUVEC", "RPTEC")

```

## miRNA overlaps in five senescent cell types

```{r, echo=FALSE, fig.height=8, fig.width=8}
venn(df_list_up, zcolor = c("#F37B59", "#9590FF", "#00C1AA", "#00ABFD", "#E76BF3"), sncs = 1.4, ilcs = 2.2, box = FALSE, opacity = 0.4)
venn(df_list_down, zcolor = c("#9590FF", "#F37B59", "#00C1AA", "#00ABFD", "#E76BF3"), sncs = 1.4, ilcs = 2.2, box = FALSE, opacity = 0.4)
venn.diagram(x = df_list_up, filename = '/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/venn_miRNA_up.png',
             col=c("#9590FF", "#F37B59", "#00C1AA", "#00ABFD", "#E76BF3"),
             fill = c(alpha("#9590FF",0.1), alpha('#F37B59',0.1), alpha('#00C1AA',0.1), alpha('#00ABFD',0.1), alpha('#E76BF3',0.1)))
venn.diagram(x = df_list_down, filename = '/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/venn_miRNA_down.png',
             col=c("#9590FF", "#F37B59", "#00C1AA", "#00ABFD", "#E76BF3"),
             fill = c(alpha("#9590FF",0.1), alpha('#F37B59',0.1), alpha('#00C1AA',0.1), alpha('#00ABFD',0.1), alpha('#E76BF3',0.1)))
```

## gene overlaps in five senescent cell types

```{r, echo=FALSE, fig.height=8, fig.width=8}
venn(df_list_gene_up, zcolor = c("#9590FF", "#F37B59", "#00C1AA", "#00ABFD", "#E76BF3"), sncs = 1.2, ilcs = 1.5, box = FALSE, opacity = 0.4)
venn(df_list_gene_down, zcolor = c("#9590FF", "#F37B59", "#00C1AA", "#00ABFD", "#E76BF3"), sncs = 1.2, ilcs = 1.5, box = FALSE, opacity = 0.4)

venn.diagram(x = df_list_gene_up, filename = '/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/venn_gene_up.png',
             col=c("#F37B59", "#9590FF", "#00C1AA", "#00ABFD", "#E76BF3"),
             fill = c(alpha("#9590FF",0.3), alpha('#F37B59',0.3), alpha('#00C1AA',0.3), alpha('#00ABFD',0.3), alpha('#E76BF3',0.3)))
venn.diagram(x = df_list_gene_down, filename = '/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/venn_gene_down.png',
             col=c("#F37B59", "#9590FF", "#00C1AA", "#00ABFD", "#E76BF3"),
             fill = c(alpha("#F37B59",0.3), alpha('#9590FF',0.3), alpha('#00C1AA',0.3), alpha('#00ABFD',0.3), alpha('#E76BF3',0.3)))
```

```{r, echo=TRUE, fig.height=8, fig.width=8}
#CELL upset plot UPREGULATED
listInput_CELL_up <- df_list_up

x_CELL_up <-  upset(fromList(listInput_CELL_up), order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNAs (FDR < 0.15)", sets.x.label = "DE microRNAs per cell type")


miRNAs_cell_up <- x_CELL_up$New_data
rownames(miRNAs_cell_up) <- unique(unlist(listInput_CELL_up))
core_miRNAs_up <- rownames(miRNAs_cell_up[rowSums(miRNAs_cell_up) >= 4,])

listInput_CELL_down <- df_list_down

x_CELL_down <-  upset(fromList(listInput_CELL_down), order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNAs (FDR < 0.15)", sets.x.label = "DE microRNAs per cell type")


miRNAs_cell_down <- x_CELL_down$New_data
rownames(miRNAs_cell_down) <- unique(unlist(listInput_CELL_down))
core_miRNAs_down <- rownames(miRNAs_cell_down[rowSums(miRNAs_cell_down) >= 4,])


#GENE upset plot UPREGULATED
df_list_gene_up <- lapply(df_list_gene_up, na.omit)
listInput_gene_up <- df_list_gene_up

x_gene_up <-  upset(fromList(listInput_gene_up), order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNAs (FDR < 0.15)", sets.x.label = "DE microRNAs per cell type")


genes_cell_up <- x_gene_up$New_data
rownames(genes_cell_up) <- unique(unlist(listInput_gene_up))
core_genes_up <- rownames(genes_cell_up[rowSums(genes_cell_up) >= 4,])

df_list_gene_down <- lapply(df_list_gene_down, na.omit)
listInput_gene_down <- df_list_gene_down

x_gene_down <-  upset(fromList(listInput_gene_down), order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNAs (FDR < 0.15)", sets.x.label = "DE microRNAs per cell type")


genes_cell_down <- x_gene_down$New_data
rownames(genes_cell_down) <- unique(unlist(listInput_gene_down))
core_genes_down <- rownames(genes_cell_down[rowSums(genes_cell_down) >= 4,])

```

# UPSET PLOTS DE miRNAs in-vitro

```{r, echo=FALSE, fig.height=8, fig.width=8}
print(x_CELL_up)
print(x_CELL_down)
```

```{r}
miR_families <- read.delim("/Users/weiglm/Desktop/SENOMIR/MARKDOWN/miR_family_info.txt", header = TRUE, sep = "\t", dec = ".")
miR_families_hsa <- miR_families[str_detect(miR_families$MiRBase.ID, "hsa-"),]

list_df_families_up <- list()
list_family_seed_up <- list()
list_family_up <- list()
list_df_family_up_conserved <- list()
list_family_up_conserved <- list()
for (i in selection) {
  list_df_families_up[[i]] <- miR_families_hsa[miR_families_hsa$MiRBase.ID %in% df_list_up[[i]],]
  list_family_seed_up[[i]] <- as.data.frame(cbind(unique(list_df_families_up[[i]]$miR.family), unique(list_df_families_up[[i]]$Seed.m8)))
  colnames(list_family_seed_up[[i]]) <- c("miR.family", "Seed.m8")
  list_family_up[[i]] <- unique(list_df_families_up[[i]]$miR.family)
  list_df_family_up_conserved[[i]] <- list_df_families_up[[i]][list_df_families_up[[i]]$Family.Conservation. == "1" | list_df_families_up[[i]]$Family.Conservation. == "2",]
  list_family_up_conserved[[i]] <- unique(list_df_family_up_conserved[[i]]$miR.family)
}

miR_families_hsa[miR_families_hsa$MiRBase.ID == "hsa-miR-203a-3p",]
list_df_families_down <- list()
list_family_seed_down <- list()
list_family_down <- list()
list_df_family_down_conserved <- list()
list_family_down_conserved <- list()
for (i in selection) {
  list_df_families_down[[i]] <- miR_families_hsa[miR_families_hsa$MiRBase.ID %in% df_list_down[[i]],]
  list_family_seed_down[[i]] <- as.data.frame(cbind(unique(list_df_families_down[[i]]$miR.family), unique(list_df_families_down[[i]]$Seed.m8)))
  colnames(list_family_seed_down[[i]]) <- c("miR.family", "Seed.m8")
  list_family_down[[i]] <- unique(list_df_families_down[[i]]$miR.family)
  list_df_family_down_conserved[[i]] <- list_df_families_down[[i]][list_df_families_down[[i]]$Family.Conservation. == "1" | list_df_families_down[[i]]$Family.Conservation. == "2",]
  list_family_down_conserved[[i]] <- unique(list_df_family_down_conserved[[i]]$miR.family)
}

vitro_up <-  upset(fromList(list_family_up), nsets = 5, order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNA families (FDR < 0.15)", sets.x.label = "DE microRNA families per tissue")


x1_fam_up <- unlist(list_family_up, use.names = FALSE)
x1_fam_up <- x1_fam_up[!duplicated(x1_fam_up)]
rownames(vitro_up$New_data) <- x1_fam_up
vitro_overlap <- vitro_up$New_data[rowSums(vitro_up$New_data) >= 4,]
vitro_overlap <- vitro_overlap[order(rowSums(vitro_overlap), decreasing = TRUE),]

vitro_heat_up <- Heatmap(vitro_overlap, cluster_rows = FALSE, cluster_columns = FALSE, row_names_max_width = max_text_width(
        rownames(vitro_overlap), 
        gp = gpar(fontsize = 12)),
        rect_gp = gpar(col = "black", lwd = 1), col = c("white", "#E76BF3"))

vitro_down <-  upset(fromList(list_family_down), nsets = 5, order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNA families (FDR < 0.15)", sets.x.label = "DE microRNA families per tissue")


x1_fam_down <- unlist(list_family_down, use.names = FALSE)
x1_fam_down <- x1_fam_down[!duplicated(x1_fam_down)]
rownames(vitro_down$New_data) <- x1_fam_down
vitro_overlap <- vitro_down$New_data[rowSums(vitro_down$New_data) >= 4,]
vitro_overlap <- vitro_overlap[order(rowSums(vitro_overlap), decreasing = TRUE),]
vitro_heat_down <- Heatmap(vitro_overlap, cluster_rows = FALSE, cluster_columns = FALSE, row_names_max_width = max_text_width(
        rownames(vitro_overlap), 
        gp = gpar(fontsize = 12)),
        rect_gp = gpar(col = "black", lwd = 1), col = c("white", "#00ABFD"))

```

# VENN in-vitro miRNA families

```{r, echo=FALSE, fig.height=6.9, fig.width=7}
venn(list_family_up, zcolor = "style", sncs = 1.2, ilcs = 1.3, box = FALSE)
venn(list_family_down, zcolor = "style", sncs = 1.2, ilcs = 1.3, box = FALSE)
print(vitro_heat_up)
print(vitro_heat_down)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load packages
library(UpSetR)
library(stringr)
library(gplots)
library(devtools)
library(ComplexHeatmap)
library(clipr)
library(purrr)

#load targetscan miR_family data
miR_families <- read.delim("/Users/weiglm/Desktop/SENOMIR/MARKDOWN/miR_family_info.txt", header = TRUE, sep = "\t", dec = ".")
miR_families_mmu <- miR_families[str_detect(miR_families$MiRBase.ID, "mmu-"),]


#load microRNA DE data TISSUES
#blood_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/03-MAYO/06-NGS-BU2-cohort-NovaSeq/01-edgeR-stats/blood_edgeR.txt", header = TRUE, sep #= "\t", dec = ".")

brain_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_brain.txt", header = TRUE, sep = "\t", dec = ".")
epi_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_fat.txt", header = TRUE, sep = "\t", dec = ".")
kidney_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_kidney.txt", header = TRUE, sep = "\t", dec = ".")
liver_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_liver.txt", header = TRUE, sep = "\t", dec = ".")
lung_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_lung.txt", header = TRUE, sep = "\t", dec = ".")
muscle_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_muscle.txt", header = TRUE, sep = "\t", dec = ".")
skin_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_skin.txt", header = TRUE, sep = "\t", dec = ".")

plasma_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_plasma.txt", header = TRUE, sep = "\t", dec = ".")
ev_edgeR <- read.delim("/Users/weiglm/Desktop/SENOMIR/14-Manuscript/DATA/edgeR_ev.txt", header = TRUE, sep = "\t", dec = ".")

blood_edgeR$miRNA <- as.factor(blood_edgeR$miRNA)
brain_edgeR$miRNA <- as.factor(brain_edgeR$miRNA)
epi_edgeR$miRNA <- as.factor(epi_edgeR$miRNA)
kidney_edgeR$miRNA <- as.factor(kidney_edgeR$miRNA)
liver_edgeR$miRNA <- as.factor(liver_edgeR$miRNA)
lung_edgeR$miRNA <- as.factor(lung_edgeR$miRNA)
muscle_edgeR$miRNA <- as.factor(muscle_edgeR$miRNA)
skin_edgeR$miRNA <- as.factor(skin_edgeR$miRNA)

plasma_edgeR$miRNA <- as.factor(plasma_edgeR$miRNA)
ev_edgeR$miRNA <- as.factor(ev_edgeR$miRNA)

df_edgeR <- list(brain_edgeR, epi_edgeR, kidney_edgeR, 
                liver_edgeR, lung_edgeR, muscle_edgeR, skin_edgeR)

names(df_edgeR) <- c("brain_edgeR", "epi_edgeR", "kidney_edgeR",
                     "liver_edgeR", "lung_edgeR", "muscle_edgeR", "skin_edgeR")

df_plasma <- list(plasma_edgeR, ev_edgeR)
names(df_plasma) <- c("plasma_edgeR", "ev_edgeR")

#AGING UP
df_edgeR_up <- list()
for (i in names(df_edgeR)) {
  df_edgeR_up[[i]] <- df_edgeR[[i]][df_edgeR[[i]]$FDR < 0.15 & df_edgeR[[i]]$logFC > 0,]$miRNA
}

list_mmu_df_families_up <- list()
list_mmu_family_seed_up <- list()
list_mmu_family_up <- list()
list_mmu_df_families_up_conserved <- list()
list_mmu_family_up_conserved <- list()
for (i in names(df_edgeR)) {
  list_mmu_df_families_up[[i]] <- miR_families_mmu[miR_families_mmu$MiRBase.ID %in% df_edgeR_up[[i]],]
  list_mmu_family_seed_up[[i]] <- as.data.frame(cbind(unique(list_mmu_df_families_up[[i]]$miR.family), unique(list_mmu_df_families_up[[i]]$Seed.m8)))
  colnames(list_mmu_family_seed_up[[i]]) <- c("miR.family", "Seed.m8")
  list_mmu_family_up[[i]] <- unique(list_mmu_df_families_up[[i]]$miR.family)
  list_mmu_df_families_up_conserved[[i]] <- list_mmu_df_families_up[[i]][list_mmu_df_families_up[[i]]$Family.Conservation. == "1" | list_mmu_df_families_up[[i]]$Family.Conservation. == "2",]
  list_mmu_family_up_conserved[[i]] <- unique(list_mmu_df_families_up_conserved[[i]]$miR.family)
  }


listInput_TISSUE <- list_mmu_family_up

upset_up <-  upset(fromList(listInput_TISSUE), nsets = 7, order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNA families (FDR < 0.15)", sets.x.label = "DE microRNA families per tissue")


x1_TISSUE <- unlist(listInput_TISSUE, use.names = FALSE)
x1_TISSUE <- x1_TISSUE[!duplicated(x1_TISSUE)]
rownames(upset_up$New_data) <- x1_TISSUE
tissue_overlap_all <- upset_up$New_data
tissue_overlap <- upset_up$New_data[rowSums(upset_up$New_data[1:7]) >= 3,]
tissue_overlap <- tissue_overlap[order(rowSums(tissue_overlap), decreasing = TRUE),]
colnames(tissue_overlap) <- c("BRAIN", "FAT", "KIDNEY", "LIVER", "LUNG", "MUSCLE", "SKIN")

heat_up <- Heatmap(tissue_overlap, cluster_rows = FALSE, cluster_columns = FALSE, row_names_gp = grid::gpar(fontsize = 10),
        rect_gp = gpar(col = "black", lwd = 1), col = c("white", "#E76BF3"))

write.table(upset_up$New_data, "/Users/weiglm/Desktop/Projects/06-SKIN/senomiR_aging_families_up.txt", dec = ".", row.names = TRUE, col.names = TRUE)

#AGING UP & IN-VITRO
list_up_conserved <- c(list_mmu_family_up_conserved, list_family_up_conserved)
listInput_mmu_hsa <- list_up_conserved

upset_mmu_hsa_up <-  upset(fromList(listInput_mmu_hsa), nsets = 12, order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNA families (FDR < 0.15)", sets.x.label = "DE microRNA families per tissue")

x1_mmu_hsa <- unlist(listInput_mmu_hsa, use.names = FALSE)
x1_mmu_hsa <- x1_mmu_hsa[!duplicated(x1_mmu_hsa)]
rownames(upset_mmu_hsa_up$New_data) <- x1_mmu_hsa
mmu_hsa_overlap <- upset_mmu_hsa_up$New_data[rowSums(upset_mmu_hsa_up$New_data[1:7]) >= 1,]
mmu_hsa_overlap <- mmu_hsa_overlap[rowSums(mmu_hsa_overlap[8:12]) >= 1,]
mmu_hsa_overlap <- mmu_hsa_overlap[order(rowSums(mmu_hsa_overlap), decreasing = TRUE),]
colnames(mmu_hsa_overlap) <- c("BRAIN","FAT", "KIDNEY", "LIVER", "LUNG", "MUSCLE", "SKIN", "ASC", "HDF", "HDMVEC", "HUVEC", "RPTEC")
column_split = rep("group1", 12)
column_split[1:7] = "in-vivo [mmu]"
column_split[8:12] = "in-vitro [hsa]"
mmu_hsa_heat_up <- Heatmap(mmu_hsa_overlap, cluster_rows = FALSE, cluster_columns = FALSE,
        rect_gp = gpar(col = "black", lwd = 1), col = c("white", "#E76BF3"), border = TRUE, column_split = column_split)


#AGING DOWN
df_edgeR_down <- list()
for (i in names(df_edgeR)) {
  df_edgeR_down[[i]] <- df_edgeR[[i]][df_edgeR[[i]]$FDR < 0.15 & df_edgeR[[i]]$logFC < 0,]$miRNA
}

list_mmu_df_families_down <- list()
list_mmu_family_seed_down <- list()
list_mmu_family_down <- list()
list_mmu_df_families_down_conserved <- list()
list_mmu_family_down_conserved <- list()
for (i in names(df_edgeR)) {
  list_mmu_df_families_down[[i]] <- miR_families_mmu[miR_families_mmu$MiRBase.ID %in% df_edgeR_down[[i]],]
  list_mmu_family_seed_down[[i]] <- as.data.frame(cbind(unique(list_mmu_df_families_down[[i]]$miR.family), unique(list_mmu_df_families_down[[i]]$Seed.m8)))
  colnames(list_mmu_family_seed_down[[i]]) <- c("miR.family", "Seed.m8")
  list_mmu_family_down[[i]] <- unique(list_mmu_df_families_down[[i]]$miR.family)
  list_mmu_df_families_down_conserved[[i]] <- list_mmu_df_families_down[[i]][list_mmu_df_families_down[[i]]$Family.Conservation. == "1" | list_mmu_df_families_down[[i]]$Family.Conservation. == "2",]
  list_mmu_family_down_conserved[[i]] <- unique(list_mmu_df_families_down_conserved[[i]]$miR.family)
  }


listInput_down <- list_mmu_family_down

upset_down <-  upset(fromList(listInput_down), nsets = 7, order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNA families (FDR < 0.15)", sets.x.label = "DE microRNA families per tissue")

x1_down <- unlist(listInput_down, use.names = FALSE)
x1_down <- x1_down[!duplicated(x1_down)]
rownames(upset_down$New_data) <- x1_down
tissue_overlap_down_all <- upset_down$New_data
tissue_overlap_down <- upset_down$New_data[rowSums(upset_down$New_data) >= 3,]
tissue_overlap_down <- tissue_overlap_down[order(rowSums(tissue_overlap_down), decreasing = TRUE),]
colnames(tissue_overlap_down) <- c("BRAIN", "FAT", "KIDNEY", "LIVER", "LUNG", "MUSCLE", "SKIN")
heat_down <- Heatmap(tissue_overlap_down, cluster_rows = FALSE, cluster_columns = FALSE,
        rect_gp = gpar(col = "black", lwd = 1), col = c("white", "#00ABFD"), row_names_rot = 0, row_names_gp = grid::gpar(fontsize = 8))

heat_down <- Heatmap(tissue_overlap_down, cluster_rows = FALSE, cluster_columns = FALSE, row_names_gp = grid::gpar(fontsize = 10),
        rect_gp = gpar(col = "black", lwd = 1), col = c("white", "#00ABFD"))

write.table(upset_down$New_data, "/Users/weiglm/Desktop/Projects/06-SKIN/senomiR_aging_families_down.txt", dec = ".", row.names = TRUE, col.names = TRUE)

#AGIND DOWN & IN-VITRO
list_down_conserved <- c(list_mmu_family_down_conserved, list_family_down_conserved)
listInput_mmu_hsa_down <- list_down_conserved

upset_mmu_hsa_down <-  upset(fromList(listInput_mmu_hsa_down), nsets = 12, order.by = "degree", point.size = 3.5, line.size = 2,
                 mainbar.y.label = "DE microRNA families (FDR < 0.15)", sets.x.label = "DE microRNA families per tissue")

x1_mmu_hsa_down <- unlist(listInput_mmu_hsa_down, use.names = FALSE)
x1_mmu_hsa_down <- x1_mmu_hsa_down[!duplicated(x1_mmu_hsa_down)]
rownames(upset_mmu_hsa_down$New_data) <- x1_mmu_hsa_down
mmu_hsa_overlap_down <- upset_mmu_hsa_down$New_data[rowSums(upset_mmu_hsa_down$New_data[1:7]) >= 1,]
mmu_hsa_overlap_down <- mmu_hsa_overlap_down[rowSums(mmu_hsa_overlap_down[8:12]) >= 1,]
mmu_hsa_overlap_down <- mmu_hsa_overlap_down[order(rowSums(mmu_hsa_overlap_down), decreasing = TRUE),]
colnames(mmu_hsa_overlap_down) <- c("BRAIN","FAT", "KIDNEY", "LIVER", "LUNG", "MUSCLE", "SKIN", "ASC", "HDF", "HDMVEC", "HUVEC", "RPTEC")
column_split = rep("group1", 12)
column_split[1:7] = "in-vivo [mmu]"
column_split[8:12] = "in-vitro [hsa]"
mmu_hsa_heat_down <- Heatmap(mmu_hsa_overlap_down, cluster_rows = FALSE, cluster_columns = FALSE,
        rect_gp = gpar(col = "black", lwd = 1), col = c("white", "#00ABFD"), border = TRUE, column_split = column_split)


```

# OVERLAPS miRNA families in-vivo

```{r, echo=FALSE, fig.height=8, fig.width=8}
print(upset_up)
print(upset_down)

```
```{r, echo=FALSE, fig.height=7, fig.width=6}
print(heat_up)
print(heat_down)
print(mmu_hsa_heat_up)
print(mmu_hsa_heat_down)
```


```{r}
n_families_up <- nrow(tissue_overlap_all)
n_families_up_3 <- nrow(tissue_overlap_all[rowSums(tissue_overlap_all) >= 3,])
n_families_up_2 <- nrow(tissue_overlap_all[rowSums(tissue_overlap_all) == 2,])
n_families_up_private <- nrow(tissue_overlap_all[rowSums(tissue_overlap_all) == 1,])

up_pie <- c(n_families_up_private, n_families_up_2, n_families_up_3)

n_families_down <- nrow(tissue_overlap_down_all)

n_families_down_3 <- nrow(tissue_overlap_down_all[rowSums(tissue_overlap_down_all) >= 3,])
n_families_down_2 <- nrow(tissue_overlap_down_all[rowSums(tissue_overlap_down_all) == 2,])
n_families_down_private <- nrow(tissue_overlap_down_all[rowSums(tissue_overlap_down_all) == 1,])

down_pie <- c(n_families_down_private, n_families_down_2, n_families_down_3)

# Create df UP
up_pie_df <- data.frame(
  group=c("Single Tissue", "Two Tissues", "3 or more"),
  value=up_pie
)
up_pie_df
# Create df DOWN
down_pie_df <- data.frame(
  group=c("Single Tissue", "Two Tissues", "3 or more"),
  value=down_pie
)


# Basic piechart
plot_pie_up <- ggplot(up_pie_df, aes(x="", y=value, fill=group)) + scale_fill_manual(values = c("#E76BF3", "#00C1AA","#9590FF")) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() # remove background, grid, numeric labels

plot_pie_down <- ggplot(down_pie_df, aes(x="", y=value, fill=group)) + scale_fill_manual(values = c("#00ABFD", "#00C1AA","lightblue")) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() # remove background, grid, numeric labels

down_pie_df
```

```{r, echo=FALSE, fig.height=12, fig.width=12}
print(plot_pie_up)
print(plot_pie_down)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
